{% set version = "1.5.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-dgof
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dgof_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dgof/dgof_{{ version }}.tar.gz
  sha256: fa2376149291f278bf6d702df24c0e7a9fe88c9be1562da8ea4660ac23986014

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('dgof')"           # [not win]
    - "\"%R%\" -e \"library('dgof')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=dgof
  license: GPL-2.0-or-later
  summary: This package contains a proposed revision to the stats::ks.test() function and the associated ks.test.Rd help page.  With one minor exception, it does not change the existing behavior of ks.test(), and it adds features necessary for doing one-sample tests with hypothesized discrete distributions.  The package
    also contains cvm.test(), for doing one-sample Cramer-von Mises goodness-of-fit tests.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: dgof
# Version: 1.2
# Date: 2012-08-03
# Title: Discrete Goodness-of-Fit Tests
# Author: Taylor B. Arnold, John W. Emerson, R Core Team and contributors worldwide
# Maintainer: Taylor B. Arnold <taylor.b.arnold@gmail.com>
# Description: This package contains a proposed revision to the stats::ks.test() function and the associated ks.test.Rd help page.  With one minor exception, it does not change the existing behavior of ks.test(), and it adds features necessary for doing one-sample tests with hypothesized discrete distributions.  The package also contains cvm.test(), for doing one-sample Cramer-von Mises goodness-of-fit tests.
# License: GPL (>= 2.0)
# LazyLoad: yes
# Packaged: 2013-10-25 02:31:43 UTC; tba3
# Repository: CRAN
# Date/Publication: 2013-10-25 14:42:46
# NeedsCompilation: yes
